[0m16:26:30.777651 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105bde870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106ad0980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106ad0680>]}


============================== 16:26:30.780767 | 50d61dd8-6802-4ba5-bd93-c63d1b208ec9 ==============================
[0m16:26:30.780767 [info ] [MainThread]: Running with dbt=1.9.1
[0m16:26:30.781097 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/friedrichtenhagen/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt seed', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:26:30.781406 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/friedrichtenhagen/coding/online_shop_efficiency_analysis/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:26:30.782757 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.047663417, "process_in_blocks": "0", "process_kernel_time": 0.112089, "process_mem_max_rss": "96043008", "process_out_blocks": "0", "process_user_time": 0.66965}
[0m16:26:30.784073 [debug] [MainThread]: Command `dbt seed` failed at 16:26:30.784015 after 0.05 seconds
[0m16:26:30.784289 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063e7bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106176540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1064e9520>]}
[0m16:26:30.784486 [debug] [MainThread]: Flushing usage events
[0m16:26:31.300775 [debug] [MainThread]: An error was encountered while trying to flush usage events
